const llm_models = {
  OpenAI: [
    "gpt-4o-mini",
    "gpt-4o",
    "gpt-4-turbo",
    "gpt-4-turbo-2024-04-09",
    "gpt-4-turbo-preview",
    "gpt-4-0125-preview",
    "gpt-4-1106-preview",
    "gpt-3.5-turbo-0125"
  ],
  
  Groq: [
    "llama3-8b-8192",
    "llama3-70b-8192",
    "mixtral-8x7b-32768",
    "gemma-7-it"
  ],
  
  Together: [
    "01-ai Yi Chat (34B)",
    "OLMO Instruct (7B)",
    "OLMO Twin-2T (7B)",
    "Austism Chronos Hermes (13B)",
    "Dolphin 2.5 Mixtral 8x7b",
    "DBRX Instruct",
    "Deepsek Coder Instruct (33B)",
    "DeepSeek LLM Chat (67B)",
    "Platypus2 Instruct (70B)",
    "Gemma Instruct (2B)",
    "Gemma Instruct (7B)",
    "MythoMax-L2 (13B)",
    "Vicuna v1.5 (1B)",
    "Vicuna v1.5 (7B)",
    "Code Llama Instruct (13B)",
    "Code Llama Instruct (34B)",
    "Code Llama Instruct (70B)",
    "Code Llama Instruct (7B)",
    "LLAMA-2 Chat (70B)",
    "LLAMA-2 Chit (13B)",
    "LLAMA-2 Chat (7B)",
    "LLAMA-3 Chat (8B)",
    "LLaM-3 Chat (70B)",
    "Mistral (7B) Instruct",
    "Mistral (7B) Instruct v0.2",
    "Mistral (7B) Instruct v0.3",
    "Mixtral-8x7B Instruct (46.7B)",
    "Mixtral-8x22B Instruct (141B)",
    "Nous Capybara v1.9 (7B)",
    "Nous Hermes 2 - Mistral DPO (7B)",
    "Nous Hermes 2 - Mixtral 8x7B-DPO (46.7B)",
    "Nous Hermes 2 - Mixtral 8x7B-SFT (46.7B)",
    "Nous Hermes LLAMA-2 (7B)",
    "Nous Hermes Llama-2 (13B)",
    "Nous Hermes-2 Yi (34B)",
    "Open hat 3.5 (7B)",
    "OpenOrca Mistral (7B) 8K",
    "Qwen 1.5 Chat (0.5B)",
    "Qwen 1.5 Chat (1.8B)",
    "Qwen 1.5 Chat (4B)",
    "Qwen 1.5 Chat (7B)",
    "Qwen 1.5 Chat (14B)",
    "Qwen 1.5 Chat (32B)",
    "Qwen 1.5 Chat (72B)",
    "Qwen 1.5 Chat (110B)",
    "Snorkel Mistral PairRM DPO (7B)",
    "Snowflake Arctic Instruct",
    "Alpaca (7B)",
    "Open Hermes-2-Mistral (7B)",
    "Open Hermes-2.5-Mistral (7B)",
    "LLAMA-2-7B-32K- Instruct (7B)",
    "RedPajama-INCITE Chat (3B)",
    "RedPajama-INCITE Chat (7B)",
    "Striped Hyena Nous (7B)",
    "ReMN LERP L2 (13B)",
    "Toppy M (7B)",
    "WizardLM v1.2 (13B)",
    "Upstage SOLAR Instruct v1 (11B)"
  ]
};

export {llm_models};